# 🧠 Expert System — Evaluation Notebook

This notebook demonstrates all required features of the Expert System project.

It is structured according to the official evaluation sheet:
- Mandatory features
- Bonus features
- Error handling
- Additional edge cases

In [1]:
from tester import show_test_string
from ExpertSystem import ExpertSystem
import pandas as pd

#AND condition and conclusion

In [2]:
show_test_string(
    "AND Condition",
    """
    B => A
    D + E => B
    G + H => F
    I + J => G
    G => H
    L + M => K
    O + P => L + N
    N => M

    =DEIJOP
    ?A
    """,
    {
        "A": "T",
		"F": "T",
		"K":"T",
		"P":"T"
    }
)

=== AND Condition ===
Query A
│   ├── Proving: A
│   │   ├── ➤ Rule: B => A
│   │   │   ├── Eval: B
│   │   │   │   ├── Proving: B
│   │   │   │   │   ├── ➤ Rule: D+E => B
│   │   │   │   │   │   ├── Eval: D+E
│   │   │   │   │   │   │   ├── Proving: D
│   │   │   │   │   │   │   │   ├── ✔ D is True (fact)
│   │   │   │   │   │   │   ├── Proving: E
│   │   │   │   │   │   │   │   ├── ✔ E is True (fact)
│   │   │   │   │   │   │   ├── Result: B = T
│   │   │   │   │   ├── Resolving: B
│   │   │   │   │   ├── Possible B: {'T'}
│   │   │   │   │   ├── Result: B = T
│   │   │   │   ├── Result: A = T
│   │   ├── Resolving: A
│   │   ├── Possible A: {'T'}
│   │   ├── Result: A = T
│   ├── Result: A = T
Query F
│   ├── Proving: F
│   │   ├── ➤ Rule: G+H => F
│   │   │   ├── Eval: G+H
│   │   │   │   ├── Proving: G
│   │   │   │   │   ├── ➤ Rule: I+J => G
│   │   │   │   │   │   ├── Eval: I+J
│   │   │   │   │   │   │   ├── Proving: I
│   │   │   │   │   │   │   │   ├── ✔ I is True (fact)
│   │   │   │   │   │   │   ├── Proving: J
│   │   │   │   │   │   │   │   ├── ✔ J is True (fact)
│   │   │   │   │   │   │   ├── Result: G = T
│   │   │   │   │   ├── Resolving: G
│   │   │   │   │   ├── Possible G: {'T'}
│   │   │   │   │   ├── Result: G = T
│   │   │   │   ├── Proving: H
│   │   │   │   │   ├── ➤ Rule: G => H
│   │   │   │   │   │   ├── Eval: G
│   │   │   │   │   │   │   ├── Proving: G
│   │   │   │   │   │   │   │   ├── ➤ Rule: I+J => G
│   │   │   │   │   │   │   │   │   ├── Eval: I+J
│   │   │   │   │   │   │   │   │   │   ├── Proving: I
│   │   │   │   │   │   │   │   │   │   │   ├── ✔ I is True (fact)
│   │   │   │   │   │   │   │   │   │   ├── Proving: J
│   │   │   │   │   │   │   │   │   │   │   ├── ✔ J is True (fact)
│   │   │   │   │   │   │   │   │   │   ├── Result: G = T
│   │   │   │   │   │   │   │   ├── Resolving: G
│   │   │   │   │   │   │   │   ├── Possible G: {'T'}
│   │   │   │   │   │   │   │   ├── Result: G = T
│   │   │   │   │   │   │   ├── Result: H = T
│   │   │   │   │   ├── Resolving: H
│   │   │   │   │   ├── Possible H: {'T'}
│   │   │   │   │   ├── Result: H = T
│   │   │   │   ├── Result: F = T
│   │   ├── Resolving: F
│   │   ├── Possible F: {'T'}
│   │   ├── Result: F = T
│   ├── Result: F = T
Query K
│   ├── Proving: K
│   │   ├── ➤ Rule: L+M => K
│   │   │   ├── Eval: L+M
│   │   │   │   ├── Proving: L
│   │   │   │   │   ├── ➤ Rule: O+P => L+N
│   │   │   │   │   │   ├── Eval: O+P
│   │   │   │   │   │   │   ├── Proving: O
│   │   │   │   │   │   │   │   ├── ✔ O is True (fact)
│   │   │   │   │   │   │   ├── Proving: P
│   │   │   │   │   │   │   │   ├── ✔ P is True (fact)
│   │   │   │   │   │   │   ├── Result: L = T
│   │   │   │   │   ├── Resolving: L+N
│   │   │   │   │   ├── Possible L: {'T'}
│   │   │   │   │   ├── Result: L = T
│   │   │   │   ├── Proving: M
│   │   │   │   │   ├── ➤ Rule: N => M
│   │   │   │   │   │   ├── Eval: N
│   │   │   │   │   │   │   ├── Proving: N
│   │   │   │   │   │   │   │   ├── ➤ Rule: O+P => L+N
│   │   │   │   │   │   │   │   │   ├── Eval: O+P
│   │   │   │   │   │   │   │   │   │   ├── Proving: O
│   │   │   │   │   │   │   │   │   │   │   ├── ✔ O is True (fact)
│   │   │   │   │   │   │   │   │   │   ├── Proving: P
│   │   │   │   │   │   │   │   │   │   │   ├── ✔ P is True (fact)
│   │   │   │   │   │   │   │   │   │   ├── Result: N = T
│   │   │   │   │   │   │   │   ├── Resolving: L+N
│   │   │   │   │   │   │   │   ├── Possible N: {'T'}
│   │   │   │   │   │   │   │   ├── Result: N = T
│   │   │   │   │   │   │   ├── Result: M = T
│   │   │   │   │   ├── Resolving: M
│   │   │   │   │   ├── Possible M: {'T'}
│   │   │   │   │   ├── Result: M = T
│   │   │   │   ├── Result: K = T
│   │   ├── Resolving: K
│   │   ├── Possible K: {'T'}
│   │   ├── Result: K = T
│   ├── Result: K = T
Query P
│   ├── Proving: P
│   │   ├── ✔ P is True (fact)
│   ├── Result: P = T

  Query Expected Got  Pass
0     A        T   T  True
1     F        T   T  True
2     K        T   T  True
3     P        T   T  True

Result: 4/4 passed

In [3]:
show_test_string(
    "AND Condition 2",
    """
    B => A
    D + E => B
    G + H => F
    I + J => G
    G => H
    L + M => K
    O + P => L + N
    N => M

    =DEIJP
    ?A
    """,
    {
        "A": "T",
		"F": "T",
		"K": "F",
		"P": "T"
    }
)

=== AND Condition 2 ===
Query A
│   ├── Proving: A
│   │   ├── ➤ Rule: B => A
│   │   │   ├── Eval: B
│   │   │   │   ├── Proving: B
│   │   │   │   │   ├── ➤ Rule: D+E => B
│   │   │   │   │   │   ├── Eval: D+E
│   │   │   │   │   │   │   ├── Proving: D
│   │   │   │   │   │   │   │   ├── ✔ D is True (fact)
│   │   │   │   │   │   │   ├── Proving: E
│   │   │   │   │   │   │   │   ├── ✔ E is True (fact)
│   │   │   │   │   │   │   ├── Result: B = T
│   │   │   │   │   ├── Resolving: B
│   │   │   │   │   ├── Possible B: {'T'}
│   │   │   │   │   ├── Result: B = T
│   │   │   │   ├── Result: A = T
│   │   ├── Resolving: A
│   │   ├── Possible A: {'T'}
│   │   ├── Result: A = T
│   ├── Result: A = T
Query F
│   ├── Proving: F
│   │   ├── ➤ Rule: G+H => F
│   │   │   ├── Eval: G+H
│   │   │   │   ├── Proving: G
│   │   │   │   │   ├── ➤ Rule: I+J => G
│   │   │   │   │   │   ├── Eval: I+J
│   │   │   │   │   │   │   ├── Proving: I
│   │   │   │   │   │   │   │   ├── ✔ I is True (fact)
│   │   │   │   │   │   │   ├── Proving: J
│   │   │   │   │   │   │   │   ├── ✔ J is True (fact)
│   │   │   │   │   │   │   ├── Result: G = T
│   │   │   │   │   ├── Resolving: G
│   │   │   │   │   ├── Possible G: {'T'}
│   │   │   │   │   ├── Result: G = T
│   │   │   │   ├── Proving: H
│   │   │   │   │   ├── ➤ Rule: G => H
│   │   │   │   │   │   ├── Eval: G
│   │   │   │   │   │   │   ├── Proving: G
│   │   │   │   │   │   │   │   ├── ➤ Rule: I+J => G
│   │   │   │   │   │   │   │   │   ├── Eval: I+J
│   │   │   │   │   │   │   │   │   │   ├── Proving: I
│   │   │   │   │   │   │   │   │   │   │   ├── ✔ I is True (fact)
│   │   │   │   │   │   │   │   │   │   ├── Proving: J
│   │   │   │   │   │   │   │   │   │   │   ├── ✔ J is True (fact)
│   │   │   │   │   │   │   │   │   │   ├── Result: G = T
│   │   │   │   │   │   │   │   ├── Resolving: G
│   │   │   │   │   │   │   │   ├── Possible G: {'T'}
│   │   │   │   │   │   │   │   ├── Result: G = T
│   │   │   │   │   │   │   ├── Result: H = T
│   │   │   │   │   ├── Resolving: H
│   │   │   │   │   ├── Possible H: {'T'}
│   │   │   │   │   ├── Result: H = T
│   │   │   │   ├── Result: F = T
│   │   ├── Resolving: F
│   │   ├── Possible F: {'T'}
│   │   ├── Result: F = T
│   ├── Result: F = T
Query K
│   ├── Proving: K
│   │   ├── ➤ Rule: L+M => K
│   │   │   ├── Eval: L+M
│   │   │   │   ├── Proving: L
│   │   │   │   │   ├── ➤ Rule: O+P => L+N
│   │   │   │   │   │   ├── Eval: O+P
│   │   │   │   │   │   │   ├── Proving: O
│   │   │   │   │   │   │   │   ├── ✘ O = F (no rule)
│   │   │   │   │   │   │   │   ├── Result: O = F
│   │   │   │   │   │   │   ├── Proving: P
│   │   │   │   │   │   │   │   ├── ✔ P is True (fact)
│   │   │   │   │   │   │   ├── Result: L = F
│   │   │   │   │   │   ├── ✘ Condition is not True (F)
│   │   │   │   │   ├── ✘ L = F (no valid rule)
│   │   │   │   │   ├── Result: L = N
│   │   │   │   ├── Proving: M
│   │   │   │   │   ├── ➤ Rule: N => M
│   │   │   │   │   │   ├── Eval: N
│   │   │   │   │   │   │   ├── Proving: N
│   │   │   │   │   │   │   │   ├── ➤ Rule: O+P => L+N
│   │   │   │   │   │   │   │   │   ├── Eval: O+P
│   │   │   │   │   │   │   │   │   │   ├── Proving: O
│   │   │   │   │   │   │   │   │   │   │   ├── ✘ O = F (no rule)
│   │   │   │   │   │   │   │   │   │   │   ├── Result: O = F
│   │   │   │   │   │   │   │   │   │   ├── Proving: P
│   │   │   │   │   │   │   │   │   │   │   ├── ✔ P is True (fact)
│   │   │   │   │   │   │   │   │   │   ├── Result: N = F
│   │   │   │   │   │   │   │   │   ├── ✘ Condition is not True (F)
│   │   │   │   │   │   │   │   ├── ✘ N = F (no valid rule)
│   │   │   │   │   │   │   │   ├── Result: N = N
│   │   │   │   │   │   │   ├── Result: M = N
│   │   │   │   │   │   ├── ✘ Condition is not True (N)
│   │   │   │   │   ├── ✘ M = F (no valid rule)
│   │   │   │   │   ├── Result: M = N
│   │   │   │   ├── Result: K = N
│   │   │   ├── ✘ Condition is not True (N)
│   │   ├── ✘ K = F (no valid rule)
│   │   ├── Result: K = N
│   ├── Result: K = N
Query P
│   ├── Proving: P
│   │   ├── ✔ P is True (fact)
│   ├── Result: P = T

  Query Expected Got  Pass
0     A        T   T  True
1     F        T   T  True
2     K        F   F  True
3     P        T   T  True

Result: 4/4 passed

# OR condition

In [ ]:
show_test_string(
    "OR Condition 1",
    """
    B + C => A
    D | E => B
    B => C

    =
    ?A
    """,
    {
        "A": "F",
    }
)

=== OR Condition 1 ===
Query A
│   ├── Proving: A
│   │   ├── ➤ Rule: B+C => A
│   │   │   ├── Eval: B+C
│   │   │   │   ├── Proving: B
│   │   │   │   │   ├── ➤ Rule: D|E => B
│   │   │   │   │   │   ├── Eval: D|E
│   │   │   │   │   │   │   ├── Proving: D
│   │   │   │   │   │   │   │   ├── ✘ D = F (no rule)
│   │   │   │   │   │   │   │   ├── Result: D = F
│   │   │   │   │   │   │   ├── Proving: E
│   │   │   │   │   │   │   │   ├── ✘ E = F (no rule)
│   │   │   │   │   │   │   │   ├── Result: E = F
│   │   │   │   │   │   │   ├── Result: B = F
│   │   │   │   │   │   ├── ✘ Condition is not True (F)
│   │   │   │   │   ├── ✘ B = F (no valid rule)
│   │   │   │   │   ├── Result: B = N
│   │   │   │   ├── Proving: C
│   │   │   │   │   ├── ➤ Rule: B => C
│   │   │   │   │   │   ├── Eval: B
│   │   │   │   │   │   │   ├── Proving: B
│   │   │   │   │   │   │   │   ├── ➤ Rule: D|E => B
│   │   │   │   │   │   │   │   │   ├── Eval: D|E
│   │   │   │   │   │   │   │   │   │   ├── Proving: D
│   │   │   │   │   │   │   │   │   │   │   ├── ✘ D = F (no rule)
│   │   │   │   │   │   │   │   │   │   │   ├── Result: D = F
│   │   │   │   │   │   │   │   │   │   ├── Proving: E
│   │   │   │   │   │   │   │   │   │   │   ├── ✘ E = F (no rule)
│   │   │   │   │   │   │   │   │   │   │   ├── Result: E = F
│   │   │   │   │   │   │   │   │   │   ├── Result: B = F
│   │   │   │   │   │   │   │   │   ├── ✘ Condition is not True (F)
│   │   │   │   │   │   │   │   ├── ✘ B = F (no valid rule)
│   │   │   │   │   │   │   │   ├── Result: B = N
│   │   │   │   │   │   │   ├── Result: C = N
│   │   │   │   │   │   ├── ✘ Condition is not True (N)
│   │   │   │   │   ├── ✘ C = F (no valid rule)
│   │   │   │   │   ├── Result: C = N
│   │   │   │   ├── Result: A = N
│   │   │   ├── ✘ Condition is not True (N)
│   │   ├── ✘ A = F (no valid rule)
│   │   ├── Result: A = N
│   ├── Result: A = N

  Query Expected Got  Pass
0     A        N   N  True

Result: 1/1 passed

In [ ]:
show_test_string(
    "OR Condition 2",
    """
    B + C => A
    D | E => B
    B => C

    =D
    ?A
    """,
    {
        "A": "T",
    }
)

=== OR Condition 1 ===
Query A
│   ├── Proving: A
│   │   ├── ➤ Rule: B+C => A
│   │   │   ├── Eval: B+C
│   │   │   │   ├── Proving: B
│   │   │   │   │   ├── ➤ Rule: D|E => B
│   │   │   │   │   │   ├── Eval: D|E
│   │   │   │   │   │   │   ├── Proving: D
│   │   │   │   │   │   │   │   ├── ✔ D is True (fact)
│   │   │   │   │   │   │   ├── Proving: E
│   │   │   │   │   │   │   │   ├── ✘ E = F (no rule)
│   │   │   │   │   │   │   │   ├── Result: E = F
│   │   │   │   │   │   │   ├── Result: B = T
│   │   │   │   │   ├── Resolving: B
│   │   │   │   │   ├── Possible B: {'T'}
│   │   │   │   │   ├── Result: B = T
│   │   │   │   ├── Proving: C
│   │   │   │   │   ├── ➤ Rule: B => C
│   │   │   │   │   │   ├── Eval: B
│   │   │   │   │   │   │   ├── Proving: B
│   │   │   │   │   │   │   │   ├── ➤ Rule: D|E => B
│   │   │   │   │   │   │   │   │   ├── Eval: D|E
│   │   │   │   │   │   │   │   │   │   ├── Proving: D
│   │   │   │   │   │   │   │   │   │   │   ├── ✔ D is True (fact)
│   │   │   │   │   │   │   │   │   │   ├── Proving: E
│   │   │   │   │   │   │   │   │   │   │   ├── ✘ E = F (no rule)
│   │   │   │   │   │   │   │   │   │   │   ├── Result: E = F
│   │   │   │   │   │   │   │   │   │   ├── Result: B = T
│   │   │   │   │   │   │   │   ├── Resolving: B
│   │   │   │   │   │   │   │   ├── Possible B: {'T'}
│   │   │   │   │   │   │   │   ├── Result: B = T
│   │   │   │   │   │   │   ├── Result: C = T
│   │   │   │   │   ├── Resolving: C
│   │   │   │   │   ├── Possible C: {'T'}
│   │   │   │   │   ├── Result: C = T
│   │   │   │   ├── Result: A = T
│   │   ├── Resolving: A
│   │   ├── Possible A: {'T'}
│   │   ├── Result: A = T
│   ├── Result: A = T

  Query Expected Got  Pass
0     A        T   T  True

Result: 1/1 passed

In [16]:
show_test_string(
    "OR Condition 3",
    """
    B + C => A
    D | E => B
    B => C

    =E
    ?A
    """,
    {
        "A": "T",
    }
)

=== OR Condition 3 ===
Query A
│   ├── Proving: A
│   │   ├── ➤ Rule: B+C => A
│   │   │   ├── Eval: B+C
│   │   │   │   ├── Proving: B
│   │   │   │   │   ├── ➤ Rule: D|E => B
│   │   │   │   │   │   ├── Eval: D|E
│   │   │   │   │   │   │   ├── Proving: D
│   │   │   │   │   │   │   │   ├── ✘ D = F (no rule)
│   │   │   │   │   │   │   │   ├── Result: D = F
│   │   │   │   │   │   │   ├── Proving: E
│   │   │   │   │   │   │   │   ├── ✔ E is True (fact)
│   │   │   │   │   │   │   ├── Result: B = T
│   │   │   │   │   ├── Resolving: B
│   │   │   │   │   ├── Possible B: {'T'}
│   │   │   │   │   ├── Result: B = T
│   │   │   │   ├── Proving: C
│   │   │   │   │   ├── ➤ Rule: B => C
│   │   │   │   │   │   ├── Eval: B
│   │   │   │   │   │   │   ├── Proving: B
│   │   │   │   │   │   │   │   ├── ➤ Rule: D|E => B
│   │   │   │   │   │   │   │   │   ├── Eval: D|E
│   │   │   │   │   │   │   │   │   │   ├── Proving: D
│   │   │   │   │   │   │   │   │   │   │   ├── ✘ D = F (no rule)
│   │   │   │   │   │   │   │   │   │   │   ├── Result: D = F
│   │   │   │   │   │   │   │   │   │   ├── Proving: E
│   │   │   │   │   │   │   │   │   │   │   ├── ✔ E is True (fact)
│   │   │   │   │   │   │   │   │   │   ├── Result: B = T
│   │   │   │   │   │   │   │   ├── Resolving: B
│   │   │   │   │   │   │   │   ├── Possible B: {'T'}
│   │   │   │   │   │   │   │   ├── Result: B = T
│   │   │   │   │   │   │   ├── Result: C = T
│   │   │   │   │   ├── Resolving: C
│   │   │   │   │   ├── Possible C: {'T'}
│   │   │   │   │   ├── Result: C = T
│   │   │   │   ├── Result: A = T
│   │   ├── Resolving: A
│   │   ├── Possible A: {'T'}
│   │   ├── Result: A = T
│   ├── Result: A = T

  Query Expected Got  Pass
0     A        T   T  True

Result: 1/1 passed

In [17]:
show_test_string(
    "OR Condition 4",
    """
    B + C => A
    D | E => B
    B => C

    =DE
    ?A
    """,
    {
        "A": "T",
    }
)

=== OR Condition 4 ===
Query A
│   ├── Proving: A
│   │   ├── ➤ Rule: B+C => A
│   │   │   ├── Eval: B+C
│   │   │   │   ├── Proving: B
│   │   │   │   │   ├── ➤ Rule: D|E => B
│   │   │   │   │   │   ├── Eval: D|E
│   │   │   │   │   │   │   ├── Proving: D
│   │   │   │   │   │   │   │   ├── ✔ D is True (fact)
│   │   │   │   │   │   │   ├── Proving: E
│   │   │   │   │   │   │   │   ├── ✔ E is True (fact)
│   │   │   │   │   │   │   ├── Result: B = T
│   │   │   │   │   ├── Resolving: B
│   │   │   │   │   ├── Possible B: {'T'}
│   │   │   │   │   ├── Result: B = T
│   │   │   │   ├── Proving: C
│   │   │   │   │   ├── ➤ Rule: B => C
│   │   │   │   │   │   ├── Eval: B
│   │   │   │   │   │   │   ├── Proving: B
│   │   │   │   │   │   │   │   ├── ➤ Rule: D|E => B
│   │   │   │   │   │   │   │   │   ├── Eval: D|E
│   │   │   │   │   │   │   │   │   │   ├── Proving: D
│   │   │   │   │   │   │   │   │   │   │   ├── ✔ D is True (fact)
│   │   │   │   │   │   │   │   │   │   ├── Proving: E
│   │   │   │   │   │   │   │   │   │   │   ├── ✔ E is True (fact)
│   │   │   │   │   │   │   │   │   │   ├── Result: B = T
│   │   │   │   │   │   │   │   ├── Resolving: B
│   │   │   │   │   │   │   │   ├── Possible B: {'T'}
│   │   │   │   │   │   │   │   ├── Result: B = T
│   │   │   │   │   │   │   ├── Result: C = T
│   │   │   │   │   ├── Resolving: C
│   │   │   │   │   ├── Possible C: {'T'}
│   │   │   │   │   ├── Result: C = T
│   │   │   │   ├── Result: A = T
│   │   ├── Resolving: A
│   │   ├── Possible A: {'T'}
│   │   ├── Result: A = T
│   ├── Result: A = T

  Query Expected Got  Pass
0     A        T   T  True

Result: 1/1 passed

# XOR condition

In [37]:
show_test_string(
    "XOR Condition 1",
    """
    B + C => A
	D ^ E => B
	B => C

    =
    ?A
    """,
    {
        "A": "F",
    }
)

=== XOR Condition 1 ===
Query A
│   ├── Proving: A
│   │   ├── ➤ Rule: B+C => A
│   │   │   ├── Eval: B+C
│   │   │   │   ├── Proving: B
│   │   │   │   │   ├── ➤ Rule: D^E => B
│   │   │   │   │   │   ├── Eval: D^E
│   │   │   │   │   │   │   ├── Proving: D
│   │   │   │   │   │   │   │   ├── ✘ D = F (no rule)
│   │   │   │   │   │   │   │   ├── Result: D = F
│   │   │   │   │   │   │   ├── Proving: E
│   │   │   │   │   │   │   │   ├── ✘ E = F (no rule)
│   │   │   │   │   │   │   │   ├── Result: E = F
│   │   │   │   │   │   │   ├── Result: B = N
│   │   │   │   │   │   ├── ✘ Condition is not True (F)
│   │   │   │   │   ├── ✘ B = F (no valid rule)
│   │   │   │   │   ├── Result: B = N
│   │   │   │   ├── Proving: C
│   │   │   │   │   ├── ➤ Rule: B => C
│   │   │   │   │   │   ├── Eval: B
│   │   │   │   │   │   │   ├── Proving: B
│   │   │   │   │   │   │   │   ├── ➤ Rule: D^E => B
│   │   │   │   │   │   │   │   │   ├── Eval: D^E
│   │   │   │   │   │   │   │   │   │   ├── Proving: D
│   │   │   │   │   │   │   │   │   │   │   ├── ✘ D = F (no rule)
│   │   │   │   │   │   │   │   │   │   │   ├── Result: D = F
│   │   │   │   │   │   │   │   │   │   ├── Proving: E
│   │   │   │   │   │   │   │   │   │   │   ├── ✘ E = F (no rule)
│   │   │   │   │   │   │   │   │   │   │   ├── Result: E = F
│   │   │   │   │   │   │   │   │   │   ├── Result: B = N
│   │   │   │   │   │   │   │   │   ├── ✘ Condition is not True (F)
│   │   │   │   │   │   │   │   ├── ✘ B = F (no valid rule)
│   │   │   │   │   │   │   │   ├── Result: B = N
│   │   │   │   │   │   │   ├── Result: C = N
│   │   │   │   │   │   ├── ✘ Condition is not True (N)
│   │   │   │   │   ├── ✘ C = F (no valid rule)
│   │   │   │   │   ├── Result: C = N
│   │   │   │   ├── Result: A = N
│   │   │   ├── ✘ Condition is not True (N)
│   │   ├── ✘ A = F (no valid rule)
│   │   ├── Result: A = N
│   ├── Result: A = N

  Query Expected Got  Pass
0     A        F   F  True

Result: 1/1 passed

In [38]:
show_test_string(
    "XOR Condition 2",
    """
    B + C => A
	D ^ E => B
	B => C

    =D
    ?A
    """,
    {
        "A": "T",
    }
)

=== XOR Condition 2 ===
Query A
│   ├── Proving: A
│   │   ├── ➤ Rule: B+C => A
│   │   │   ├── Eval: B+C
│   │   │   │   ├── Proving: B
│   │   │   │   │   ├── ➤ Rule: D^E => B
│   │   │   │   │   │   ├── Eval: D^E
│   │   │   │   │   │   │   ├── Proving: D
│   │   │   │   │   │   │   │   ├── ✔ D is True (fact)
│   │   │   │   │   │   │   ├── Proving: E
│   │   │   │   │   │   │   │   ├── ✘ E = F (no rule)
│   │   │   │   │   │   │   │   ├── Result: E = F
│   │   │   │   │   │   │   ├── Result: B = T
│   │   │   │   │   ├── Resolving: B
│   │   │   │   │   ├── Possible B: {'T'}
│   │   │   │   │   ├── Result: B = T
│   │   │   │   ├── Proving: C
│   │   │   │   │   ├── ➤ Rule: B => C
│   │   │   │   │   │   ├── Eval: B
│   │   │   │   │   │   │   ├── Proving: B
│   │   │   │   │   │   │   │   ├── ➤ Rule: D^E => B
│   │   │   │   │   │   │   │   │   ├── Eval: D^E
│   │   │   │   │   │   │   │   │   │   ├── Proving: D
│   │   │   │   │   │   │   │   │   │   │   ├── ✔ D is True (fact)
│   │   │   │   │   │   │   │   │   │   ├── Proving: E
│   │   │   │   │   │   │   │   │   │   │   ├── ✘ E = F (no rule)
│   │   │   │   │   │   │   │   │   │   │   ├── Result: E = F
│   │   │   │   │   │   │   │   │   │   ├── Result: B = T
│   │   │   │   │   │   │   │   ├── Resolving: B
│   │   │   │   │   │   │   │   ├── Possible B: {'T'}
│   │   │   │   │   │   │   │   ├── Result: B = T
│   │   │   │   │   │   │   ├── Result: C = T
│   │   │   │   │   ├── Resolving: C
│   │   │   │   │   ├── Possible C: {'T'}
│   │   │   │   │   ├── Result: C = T
│   │   │   │   ├── Result: A = T
│   │   ├── Resolving: A
│   │   ├── Possible A: {'T'}
│   │   ├── Result: A = T
│   ├── Result: A = T

  Query Expected Got  Pass
0     A        T   T  True

Result: 1/1 passed

In [22]:
show_test_string(
    "XOR Condition 3",
    """
    B + C => A
	D ^ E => B
	B => C

    =E
    ?A
    """,
    {
        "A": "T",
    }
)

=== XOR Condition 3 ===
Query A
│   ├── Proving: A
│   │   ├── ➤ Rule: B+C => A
│   │   │   ├── Eval: B+C
│   │   │   │   ├── Proving: B
│   │   │   │   │   ├── ➤ Rule: D^E => B
│   │   │   │   │   │   ├── Eval: D^E
│   │   │   │   │   │   │   ├── Proving: D
│   │   │   │   │   │   │   │   ├── ✘ D = F (no rule)
│   │   │   │   │   │   │   │   ├── Result: D = F
│   │   │   │   │   │   │   ├── Proving: E
│   │   │   │   │   │   │   │   ├── ✔ E is True (fact)
│   │   │   │   │   │   │   ├── Result: B = T
│   │   │   │   │   ├── Resolving: B
│   │   │   │   │   ├── Possible B: {'T'}
│   │   │   │   │   ├── Result: B = T
│   │   │   │   ├── Proving: C
│   │   │   │   │   ├── ➤ Rule: B => C
│   │   │   │   │   │   ├── Eval: B
│   │   │   │   │   │   │   ├── Proving: B
│   │   │   │   │   │   │   │   ├── ➤ Rule: D^E => B
│   │   │   │   │   │   │   │   │   ├── Eval: D^E
│   │   │   │   │   │   │   │   │   │   ├── Proving: D
│   │   │   │   │   │   │   │   │   │   │   ├── ✘ D = F (no rule)
│   │   │   │   │   │   │   │   │   │   │   ├── Result: D = F
│   │   │   │   │   │   │   │   │   │   ├── Proving: E
│   │   │   │   │   │   │   │   │   │   │   ├── ✔ E is True (fact)
│   │   │   │   │   │   │   │   │   │   ├── Result: B = T
│   │   │   │   │   │   │   │   ├── Resolving: B
│   │   │   │   │   │   │   │   ├── Possible B: {'T'}
│   │   │   │   │   │   │   │   ├── Result: B = T
│   │   │   │   │   │   │   ├── Result: C = T
│   │   │   │   │   ├── Resolving: C
│   │   │   │   │   ├── Possible C: {'T'}
│   │   │   │   │   ├── Result: C = T
│   │   │   │   ├── Result: A = T
│   │   ├── Resolving: A
│   │   ├── Possible A: {'T'}
│   │   ├── Result: A = T
│   ├── Result: A = T

  Query Expected Got  Pass
0     A        T   T  True

Result: 1/1 passed

In [39]:
show_test_string(
    "XOR Condition 4",
    """
    B + C => A
	D ^ E => B
	B => C

    =DE
    ?A
    """,
    {
        "A": "F",
    }
)

=== XOR Condition 4 ===
Query A
│   ├── Proving: A
│   │   ├── ➤ Rule: B+C => A
│   │   │   ├── Eval: B+C
│   │   │   │   ├── Proving: B
│   │   │   │   │   ├── ➤ Rule: D^E => B
│   │   │   │   │   │   ├── Eval: D^E
│   │   │   │   │   │   │   ├── Proving: D
│   │   │   │   │   │   │   │   ├── ✔ D is True (fact)
│   │   │   │   │   │   │   ├── Proving: E
│   │   │   │   │   │   │   │   ├── ✔ E is True (fact)
│   │   │   │   │   │   │   ├── Result: B = N
│   │   │   │   │   │   ├── ✘ Condition is not True (F)
│   │   │   │   │   ├── ✘ B = F (no valid rule)
│   │   │   │   │   ├── Result: B = N
│   │   │   │   ├── Proving: C
│   │   │   │   │   ├── ➤ Rule: B => C
│   │   │   │   │   │   ├── Eval: B
│   │   │   │   │   │   │   ├── Proving: B
│   │   │   │   │   │   │   │   ├── ➤ Rule: D^E => B
│   │   │   │   │   │   │   │   │   ├── Eval: D^E
│   │   │   │   │   │   │   │   │   │   ├── Proving: D
│   │   │   │   │   │   │   │   │   │   │   ├── ✔ D is True (fact)
│   │   │   │   │   │   │   │   │   │   ├── Proving: E
│   │   │   │   │   │   │   │   │   │   │   ├── ✔ E is True (fact)
│   │   │   │   │   │   │   │   │   │   ├── Result: B = N
│   │   │   │   │   │   │   │   │   ├── ✘ Condition is not True (F)
│   │   │   │   │   │   │   │   ├── ✘ B = F (no valid rule)
│   │   │   │   │   │   │   │   ├── Result: B = N
│   │   │   │   │   │   │   ├── Result: C = N
│   │   │   │   │   │   ├── ✘ Condition is not True (N)
│   │   │   │   │   ├── ✘ C = F (no valid rule)
│   │   │   │   │   ├── Result: C = N
│   │   │   │   ├── Result: A = N
│   │   │   ├── ✘ Condition is not True (N)
│   │   ├── ✘ A = F (no valid rule)
│   │   ├── Result: A = N
│   ├── Result: A = N

  Query Expected Got  Pass
0     A        F   F  True

Result: 1/1 passed

# Negation

In [40]:
show_test_string(
    "Negation 1",
    """
    B + !C => A
    =
    ?A
    """,
    {
        "A": "F",
    }
)

=== Negation 1 ===
Query A
│   ├── Proving: A
│   │   ├── ➤ Rule: B+!C => A
│   │   │   ├── Eval: B+!C
│   │   │   │   ├── Proving: B
│   │   │   │   │   ├── ✘ B = F (no rule)
│   │   │   │   │   ├── Result: B = F
│   │   │   │   ├── Proving: C
│   │   │   │   │   ├── ✘ C = F (no rule)
│   │   │   │   │   ├── Result: C = F
│   │   │   │   ├── Result: A = F
│   │   │   ├── ✘ Condition is not True (F)
│   │   ├── ✘ A = F (no valid rule)
│   │   ├── Result: A = N
│   ├── Result: A = N

  Query Expected Got  Pass
0     A        F   F  True

Result: 1/1 passed

In [41]:
show_test_string(
    "Negation 2",
    """
    B + !C => A
    =B
    ?A
    """,
    {
        "A": "T",
    }
)

=== Negation 2 ===
Query A
│   ├── Proving: A
│   │   ├── ➤ Rule: B+!C => A
│   │   │   ├── Eval: B+!C
│   │   │   │   ├── Proving: B
│   │   │   │   │   ├── ✔ B is True (fact)
│   │   │   │   ├── Proving: C
│   │   │   │   │   ├── ✘ C = F (no rule)
│   │   │   │   │   ├── Result: C = F
│   │   │   │   ├── Result: A = T
│   │   ├── Resolving: A
│   │   ├── Possible A: {'T'}
│   │   ├── Result: A = T
│   ├── Result: A = T

  Query Expected Got  Pass
0     A        T   T  True

Result: 1/1 passed

In [42]:
show_test_string(
    "Negation 3",
    """
    B + !C => A
    =C
    ?A
    """,
    {
        "A": "F",
    }
)

=== Negation 3 ===
Query A
│   ├── Proving: A
│   │   ├── ➤ Rule: B+!C => A
│   │   │   ├── Eval: B+!C
│   │   │   │   ├── Proving: B
│   │   │   │   │   ├── ✘ B = F (no rule)
│   │   │   │   │   ├── Result: B = F
│   │   │   │   ├── Proving: C
│   │   │   │   │   ├── ✔ C is True (fact)
│   │   │   │   ├── Result: A = N
│   │   │   ├── ✘ Condition is not True (F)
│   │   ├── ✘ A = F (no valid rule)
│   │   ├── Result: A = N
│   ├── Result: A = N

  Query Expected Got  Pass
0     A        F   F  True

Result: 1/1 passed

In [43]:
show_test_string(
    "Negation 4",
    """
    B + !C => A
    =BC
    ?A
    """,
    {
        "A": "F",
    }
)

=== Negation 4 ===
Query A
│   ├── Proving: A
│   │   ├── ➤ Rule: B+!C => A
│   │   │   ├── Eval: B+!C
│   │   │   │   ├── Proving: B
│   │   │   │   │   ├── ✔ B is True (fact)
│   │   │   │   ├── Proving: C
│   │   │   │   │   ├── ✔ C is True (fact)
│   │   │   │   ├── Result: A = N
│   │   │   ├── ✘ Condition is not True (F)
│   │   ├── ✘ A = F (no valid rule)
│   │   ├── Result: A = N
│   ├── Result: A = N

  Query Expected Got  Pass
0     A        F   F  True

Result: 1/1 passed

# Same conclusion in multiple rules

In [44]:
show_test_string(
    "multi rule 1",
    """
    B => A
    C => A
	=
    ?A
    """,
    {
        "A": "F",
    }
)

=== multi rule 1 ===
Query A
│   ├── Proving: A
│   │   ├── ➤ Rule: B => A
│   │   │   ├── Eval: B
│   │   │   │   ├── Proving: B
│   │   │   │   │   ├── ✘ B = F (no rule)
│   │   │   │   │   ├── Result: B = F
│   │   │   │   ├── Result: A = F
│   │   │   ├── ✘ Condition is not True (F)
│   │   ├── ➤ Rule: C => A
│   │   │   ├── Eval: C
│   │   │   │   ├── Proving: C
│   │   │   │   │   ├── ✘ C = F (no rule)
│   │   │   │   │   ├── Result: C = F
│   │   │   │   ├── Result: A = F
│   │   │   ├── ✘ Condition is not True (F)
│   │   ├── ✘ A = F (no valid rule)
│   │   ├── Result: A = N
│   ├── Result: A = N

  Query Expected Got  Pass
0     A        F   F  True

Result: 1/1 passed

In [47]:
show_test_string(
    "multi rule 2",
    """
    B => A
    C => A
	=B
    ?A
    """,
    {
        "A": "T",
    }
)

=== multi rule 2 ===
Query A
│   ├── Proving: A
│   │   ├── ➤ Rule: B => A
│   │   │   ├── Eval: B
│   │   │   │   ├── Proving: B
│   │   │   │   │   ├── ✔ B is True (fact)
│   │   │   │   ├── Result: A = T
│   │   ├── Resolving: A
│   │   ├── Possible A: {'T'}
│   │   ├── ➤ Rule: C => A
│   │   │   ├── Eval: C
│   │   │   │   ├── Proving: C
│   │   │   │   │   ├── ✘ C = F (no rule)
│   │   │   │   │   ├── Result: C = F
│   │   │   │   ├── Result: A = F
│   │   │   ├── ✘ Condition is not True (F)
│   │   ├── Result: A = T
│   ├── Result: A = T

  Query Expected Got  Pass
0     A        T   T  True

Result: 1/1 passed

In [48]:
show_test_string(
    "multi rule 3",
    """
    B => A
    C => A
	=C
    ?A
    """,
    {
        "A": "T",
    }
)

=== multi rule 3 ===
Query A
│   ├── Proving: A
│   │   ├── ➤ Rule: B => A
│   │   │   ├── Eval: B
│   │   │   │   ├── Proving: B
│   │   │   │   │   ├── ✘ B = F (no rule)
│   │   │   │   │   ├── Result: B = F
│   │   │   │   ├── Result: A = F
│   │   │   ├── ✘ Condition is not True (F)
│   │   ├── ➤ Rule: C => A
│   │   │   ├── Eval: C
│   │   │   │   ├── Proving: C
│   │   │   │   │   ├── ✔ C is True (fact)
│   │   │   │   ├── Result: A = T
│   │   ├── Resolving: A
│   │   ├── Possible A: {'T'}
│   │   ├── Result: A = T
│   ├── Result: A = T

  Query Expected Got  Pass
0     A        T   T  True

Result: 1/1 passed

In [49]:
show_test_string(
    "multi rule 3",
    """
    B => A
    C => A
	=BC
    ?A
    """,
    {
        "A": "T",
    }
)

=== multi rule 3 ===
Query A
│   ├── Proving: A
│   │   ├── ➤ Rule: B => A
│   │   │   ├── Eval: B
│   │   │   │   ├── Proving: B
│   │   │   │   │   ├── ✔ B is True (fact)
│   │   │   │   ├── Result: A = T
│   │   ├── Resolving: A
│   │   ├── Possible A: {'T'}
│   │   ├── ➤ Rule: C => A
│   │   │   ├── Eval: C
│   │   │   │   ├── Proving: C
│   │   │   │   │   ├── ✔ C is True (fact)
│   │   │   │   ├── Result: A = T
│   │   ├── Resolving: A
│   │   ├── Possible A: {'T'}
│   │   ├── Result: A = T
│   ├── Result: A = T

  Query Expected Got  Pass
0     A        T   T  True

Result: 1/1 passed

# Parenthesis

In [ ]:
show_test_string(
    "parenthesis1",
    """
    A | B + C => E
	(F | G) + H => E
	=
	?E
    """,
    {
        "E": "F",
    }
)

=== parenthesis ===
Query E
│   ├── Proving: E
│   │   ├── ➤ Rule: A|B+C => E
│   │   │   ├── Eval: A|B+C
│   │   │   │   ├── Proving: A
│   │   │   │   │   ├── ✘ A = F (no rule)
│   │   │   │   │   ├── Result: A = F
│   │   │   │   ├── Proving: B
│   │   │   │   │   ├── ✘ B = F (no rule)
│   │   │   │   │   ├── Result: B = F
│   │   │   │   ├── Proving: C
│   │   │   │   │   ├── ✘ C = F (no rule)
│   │   │   │   │   ├── Result: C = F
│   │   │   │   ├── Result: E = F
│   │   │   ├── ✘ Condition is not True (F)
│   │   ├── ➤ Rule: (F|G)+H => E
│   │   │   ├── Eval: (F|G)+H
│   │   │   │   ├── Proving: F
│   │   │   │   │   ├── ✘ F = F (no rule)
│   │   │   │   │   ├── Result: F = F
│   │   │   │   ├── Proving: G
│   │   │   │   │   ├── ✘ G = F (no rule)
│   │   │   │   │   ├── Result: G = F
│   │   │   │   ├── Proving: H
│   │   │   │   │   ├── ✘ H = F (no rule)
│   │   │   │   │   ├── Result: H = F
│   │   │   │   ├── Result: E = F
│   │   │   ├── ✘ Condition is not True (F)
│   │   ├── ✘ E = F (no valid rule)
│   │   ├── Result: E = N
│   ├── Result: E = N

  Query Expected Got  Pass
0     E        F   F  True

Result: 1/1 passed

In [52]:
show_test_string(
    "parenthesis2",
    """
    A | B + C => E
	(F | G) + H => E
	=B
	?E
    """,
    {
        "E": "F",
    }
)

=== parenthesis2 ===
Query E
│   ├── Proving: E
│   │   ├── ➤ Rule: A|B+C => E
│   │   │   ├── Eval: A|B+C
│   │   │   │   ├── Proving: A
│   │   │   │   │   ├── ✘ A = F (no rule)
│   │   │   │   │   ├── Result: A = F
│   │   │   │   ├── Proving: B
│   │   │   │   │   ├── ✔ B is True (fact)
│   │   │   │   ├── Proving: C
│   │   │   │   │   ├── ✘ C = F (no rule)
│   │   │   │   │   ├── Result: C = F
│   │   │   │   ├── Result: E = F
│   │   │   ├── ✘ Condition is not True (F)
│   │   ├── ➤ Rule: (F|G)+H => E
│   │   │   ├── Eval: (F|G)+H
│   │   │   │   ├── Proving: F
│   │   │   │   │   ├── ✘ F = F (no rule)
│   │   │   │   │   ├── Result: F = F
│   │   │   │   ├── Proving: G
│   │   │   │   │   ├── ✘ G = F (no rule)
│   │   │   │   │   ├── Result: G = F
│   │   │   │   ├── Proving: H
│   │   │   │   │   ├── ✘ H = F (no rule)
│   │   │   │   │   ├── Result: H = F
│   │   │   │   ├── Result: E = F
│   │   │   ├── ✘ Condition is not True (F)
│   │   ├── ✘ E = F (no valid rule)
│   │   ├── Result: E = N
│   ├── Result: E = N

  Query Expected Got  Pass
0     E        F   F  True

Result: 1/1 passed

In [53]:
show_test_string(
    "parenthesis3",
    """
    A | B + C => E
	(F | G) + H => E
	=C
	?E
    """,
    {
        "E": "F",
    }
)

=== parenthesis3 ===
Query E
│   ├── Proving: E
│   │   ├── ➤ Rule: A|B+C => E
│   │   │   ├── Eval: A|B+C
│   │   │   │   ├── Proving: A
│   │   │   │   │   ├── ✘ A = F (no rule)
│   │   │   │   │   ├── Result: A = F
│   │   │   │   ├── Proving: B
│   │   │   │   │   ├── ✘ B = F (no rule)
│   │   │   │   │   ├── Result: B = F
│   │   │   │   ├── Proving: C
│   │   │   │   │   ├── ✔ C is True (fact)
│   │   │   │   ├── Result: E = F
│   │   │   ├── ✘ Condition is not True (F)
│   │   ├── ➤ Rule: (F|G)+H => E
│   │   │   ├── Eval: (F|G)+H
│   │   │   │   ├── Proving: F
│   │   │   │   │   ├── ✘ F = F (no rule)
│   │   │   │   │   ├── Result: F = F
│   │   │   │   ├── Proving: G
│   │   │   │   │   ├── ✘ G = F (no rule)
│   │   │   │   │   ├── Result: G = F
│   │   │   │   ├── Proving: H
│   │   │   │   │   ├── ✘ H = F (no rule)
│   │   │   │   │   ├── Result: H = F
│   │   │   │   ├── Result: E = F
│   │   │   ├── ✘ Condition is not True (F)
│   │   ├── ✘ E = F (no valid rule)
│   │   ├── Result: E = N
│   ├── Result: E = N

  Query Expected Got  Pass
0     E        F   F  True

Result: 1/1 passed

In [54]:
show_test_string(
    "parenthesis4",
    """
    A | B + C => E
	(F | G) + H => E
	=AC
	?E
    """,
    {
        "E": "T",
    }
)

=== parenthesis4 ===
Query E
│   ├── Proving: E
│   │   ├── ➤ Rule: A|B+C => E
│   │   │   ├── Eval: A|B+C
│   │   │   │   ├── Proving: A
│   │   │   │   │   ├── ✔ A is True (fact)
│   │   │   │   ├── Proving: B
│   │   │   │   │   ├── ✘ B = F (no rule)
│   │   │   │   │   ├── Result: B = F
│   │   │   │   ├── Proving: C
│   │   │   │   │   ├── ✔ C is True (fact)
│   │   │   │   ├── Result: E = T
│   │   ├── Resolving: E
│   │   ├── Possible E: {'T'}
│   │   ├── ➤ Rule: (F|G)+H => E
│   │   │   ├── Eval: (F|G)+H
│   │   │   │   ├── Proving: F
│   │   │   │   │   ├── ✘ F = F (no rule)
│   │   │   │   │   ├── Result: F = F
│   │   │   │   ├── Proving: G
│   │   │   │   │   ├── ✘ G = F (no rule)
│   │   │   │   │   ├── Result: G = F
│   │   │   │   ├── Proving: H
│   │   │   │   │   ├── ✘ H = F (no rule)
│   │   │   │   │   ├── Result: H = F
│   │   │   │   ├── Result: E = F
│   │   │   ├── ✘ Condition is not True (F)
│   │   ├── Result: E = T
│   ├── Result: E = T

  Query Expected Got  Pass
0     E        T   T  True

Result: 1/1 passed

In [55]:
show_test_string(
    "parenthesis5",
    """
    A | B + C => E
	(F | G) + H => E
	=BC
	?E
    """,
    {
        "E": "T",
    }
)

=== parenthesis5 ===
Query E
│   ├── Proving: E
│   │   ├── ➤ Rule: A|B+C => E
│   │   │   ├── Eval: A|B+C
│   │   │   │   ├── Proving: A
│   │   │   │   │   ├── ✘ A = F (no rule)
│   │   │   │   │   ├── Result: A = F
│   │   │   │   ├── Proving: B
│   │   │   │   │   ├── ✔ B is True (fact)
│   │   │   │   ├── Proving: C
│   │   │   │   │   ├── ✔ C is True (fact)
│   │   │   │   ├── Result: E = T
│   │   ├── Resolving: E
│   │   ├── Possible E: {'T'}
│   │   ├── ➤ Rule: (F|G)+H => E
│   │   │   ├── Eval: (F|G)+H
│   │   │   │   ├── Proving: F
│   │   │   │   │   ├── ✘ F = F (no rule)
│   │   │   │   │   ├── Result: F = F
│   │   │   │   ├── Proving: G
│   │   │   │   │   ├── ✘ G = F (no rule)
│   │   │   │   │   ├── Result: G = F
│   │   │   │   ├── Proving: H
│   │   │   │   │   ├── ✘ H = F (no rule)
│   │   │   │   │   ├── Result: H = F
│   │   │   │   ├── Result: E = F
│   │   │   ├── ✘ Condition is not True (F)
│   │   ├── Result: E = T
│   ├── Result: E = T

  Query Expected Got  Pass
0     E        T   T  True

Result: 1/1 passed

In [57]:
show_test_string(
    "parenthesis6",
    """
    A | B + C => E
	(F | G) + H => E
	=F
	?E
    """,
    {
        "E": "F",
    }
)

=== parenthesis6 ===
Query E
│   ├── Proving: E
│   │   ├── ➤ Rule: A|B+C => E
│   │   │   ├── Eval: A|B+C
│   │   │   │   ├── Proving: A
│   │   │   │   │   ├── ✘ A = F (no rule)
│   │   │   │   │   ├── Result: A = F
│   │   │   │   ├── Proving: B
│   │   │   │   │   ├── ✘ B = F (no rule)
│   │   │   │   │   ├── Result: B = F
│   │   │   │   ├── Proving: C
│   │   │   │   │   ├── ✘ C = F (no rule)
│   │   │   │   │   ├── Result: C = F
│   │   │   │   ├── Result: E = F
│   │   │   ├── ✘ Condition is not True (F)
│   │   ├── ➤ Rule: (F|G)+H => E
│   │   │   ├── Eval: (F|G)+H
│   │   │   │   ├── Proving: F
│   │   │   │   │   ├── ✔ F is True (fact)
│   │   │   │   ├── Proving: G
│   │   │   │   │   ├── ✘ G = F (no rule)
│   │   │   │   │   ├── Result: G = F
│   │   │   │   ├── Proving: H
│   │   │   │   │   ├── ✘ H = F (no rule)
│   │   │   │   │   ├── Result: H = F
│   │   │   │   ├── Result: E = F
│   │   │   ├── ✘ Condition is not True (F)
│   │   ├── ✘ E = F (no valid rule)
│   │   ├── Result: E = N
│   ├── Result: E = N

  Query Expected Got  Pass
0     E        F   F  True

Result: 1/1 passed

In [58]:
show_test_string(
    "parenthesis7",
    """
    A | B + C => E
	(F | G) + H => E
	=G
	?E
    """,
    {
        "E": "F",
    }
)

=== parenthesis7 ===
Query E
│   ├── Proving: E
│   │   ├── ➤ Rule: A|B+C => E
│   │   │   ├── Eval: A|B+C
│   │   │   │   ├── Proving: A
│   │   │   │   │   ├── ✘ A = F (no rule)
│   │   │   │   │   ├── Result: A = F
│   │   │   │   ├── Proving: B
│   │   │   │   │   ├── ✘ B = F (no rule)
│   │   │   │   │   ├── Result: B = F
│   │   │   │   ├── Proving: C
│   │   │   │   │   ├── ✘ C = F (no rule)
│   │   │   │   │   ├── Result: C = F
│   │   │   │   ├── Result: E = F
│   │   │   ├── ✘ Condition is not True (F)
│   │   ├── ➤ Rule: (F|G)+H => E
│   │   │   ├── Eval: (F|G)+H
│   │   │   │   ├── Proving: F
│   │   │   │   │   ├── ✘ F = F (no rule)
│   │   │   │   │   ├── Result: F = F
│   │   │   │   ├── Proving: G
│   │   │   │   │   ├── ✔ G is True (fact)
│   │   │   │   ├── Proving: H
│   │   │   │   │   ├── ✘ H = F (no rule)
│   │   │   │   │   ├── Result: H = F
│   │   │   │   ├── Result: E = F
│   │   │   ├── ✘ Condition is not True (F)
│   │   ├── ✘ E = F (no valid rule)
│   │   ├── Result: E = N
│   ├── Result: E = N

  Query Expected Got  Pass
0     E        F   F  True

Result: 1/1 passed

In [59]:
show_test_string(
    "parenthesis8",
    """
    A | B + C => E
	(F | G) + H => E
	=H
	?E
    """,
    {
        "E": "F",
    }
)

=== parenthesis8 ===
Query E
│   ├── Proving: E
│   │   ├── ➤ Rule: A|B+C => E
│   │   │   ├── Eval: A|B+C
│   │   │   │   ├── Proving: A
│   │   │   │   │   ├── ✘ A = F (no rule)
│   │   │   │   │   ├── Result: A = F
│   │   │   │   ├── Proving: B
│   │   │   │   │   ├── ✘ B = F (no rule)
│   │   │   │   │   ├── Result: B = F
│   │   │   │   ├── Proving: C
│   │   │   │   │   ├── ✘ C = F (no rule)
│   │   │   │   │   ├── Result: C = F
│   │   │   │   ├── Result: E = F
│   │   │   ├── ✘ Condition is not True (F)
│   │   ├── ➤ Rule: (F|G)+H => E
│   │   │   ├── Eval: (F|G)+H
│   │   │   │   ├── Proving: F
│   │   │   │   │   ├── ✘ F = F (no rule)
│   │   │   │   │   ├── Result: F = F
│   │   │   │   ├── Proving: G
│   │   │   │   │   ├── ✘ G = F (no rule)
│   │   │   │   │   ├── Result: G = F
│   │   │   │   ├── Proving: H
│   │   │   │   │   ├── ✔ H is True (fact)
│   │   │   │   ├── Result: E = F
│   │   │   ├── ✘ Condition is not True (F)
│   │   ├── ✘ E = F (no valid rule)
│   │   ├── Result: E = N
│   ├── Result: E = N

  Query Expected Got  Pass
0     E        F   F  True

Result: 1/1 passed

In [60]:
show_test_string(
    "parenthesis8",
    """
    A | B + C => E
	(F | G) + H => E
	=FH
	?E
    """,
    {
        "E": "T",
    }
)

=== parenthesis8 ===
Query E
│   ├── Proving: E
│   │   ├── ➤ Rule: A|B+C => E
│   │   │   ├── Eval: A|B+C
│   │   │   │   ├── Proving: A
│   │   │   │   │   ├── ✘ A = F (no rule)
│   │   │   │   │   ├── Result: A = F
│   │   │   │   ├── Proving: B
│   │   │   │   │   ├── ✘ B = F (no rule)
│   │   │   │   │   ├── Result: B = F
│   │   │   │   ├── Proving: C
│   │   │   │   │   ├── ✘ C = F (no rule)
│   │   │   │   │   ├── Result: C = F
│   │   │   │   ├── Result: E = F
│   │   │   ├── ✘ Condition is not True (F)
│   │   ├── ➤ Rule: (F|G)+H => E
│   │   │   ├── Eval: (F|G)+H
│   │   │   │   ├── Proving: F
│   │   │   │   │   ├── ✔ F is True (fact)
│   │   │   │   ├── Proving: G
│   │   │   │   │   ├── ✘ G = F (no rule)
│   │   │   │   │   ├── Result: G = F
│   │   │   │   ├── Proving: H
│   │   │   │   │   ├── ✔ H is True (fact)
│   │   │   │   ├── Result: E = T
│   │   ├── Resolving: E
│   │   ├── Possible E: {'T'}
│   │   ├── Result: E = T
│   ├── Result: E = T

  Query Expected Got  Pass
0     E        T   T  True

Result: 1/1 passed

In [61]:
show_test_string(
    "parenthesis8",
    """
    A | B + C => E
	(F | G) + H => E
	=GH
	?E
    """,
    {
        "E": "T",
    }
)

=== parenthesis8 ===
Query E
│   ├── Proving: E
│   │   ├── ➤ Rule: A|B+C => E
│   │   │   ├── Eval: A|B+C
│   │   │   │   ├── Proving: A
│   │   │   │   │   ├── ✘ A = F (no rule)
│   │   │   │   │   ├── Result: A = F
│   │   │   │   ├── Proving: B
│   │   │   │   │   ├── ✘ B = F (no rule)
│   │   │   │   │   ├── Result: B = F
│   │   │   │   ├── Proving: C
│   │   │   │   │   ├── ✘ C = F (no rule)
│   │   │   │   │   ├── Result: C = F
│   │   │   │   ├── Result: E = F
│   │   │   ├── ✘ Condition is not True (F)
│   │   ├── ➤ Rule: (F|G)+H => E
│   │   │   ├── Eval: (F|G)+H
│   │   │   │   ├── Proving: F
│   │   │   │   │   ├── ✘ F = F (no rule)
│   │   │   │   │   ├── Result: F = F
│   │   │   │   ├── Proving: G
│   │   │   │   │   ├── ✔ G is True (fact)
│   │   │   │   ├── Proving: H
│   │   │   │   │   ├── ✔ H is True (fact)
│   │   │   │   ├── Result: E = T
│   │   ├── Resolving: E
│   │   ├── Possible E: {'T'}
│   │   ├── Result: E = T
│   ├── Result: E = T

  Query Expected Got  Pass
0     E        T   T  True

Result: 1/1 passed